import Head from "next/head";
import Link from "next/link";
import labels from "@/data/labels.json";

export default function Home() {
  return (
    <>
      <Head>
        <title>Medical Costs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ padding: 60 }}>
        <ul>
          {labels.map((label) => (
            <li key={label.id}>
              <Link href={`/${label.slug}/USA`}>
                {label.label}
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </>
  );
}
